name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Week_3/SafariPark/SafariPark.sln
    - name: Build
      run: dotnet build --no-restore Week_3/SafariPark/SafariPark.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Week_3/SafariPark/SafariPark.sln
